version: '3'
services:
  policy_gateway:
    build: .
    ports:
      - "6010:5000"
    environment:
      - DEPLOYER_IP=deployer:80
      - FETCHER_IP=fetcher:80
      - POLICY_TOKEN_IP=policy_token_gateway:8080
      - MYSQL_USERNAME=user
      - MYSQL_USER_PASSWORD=mypass
      - MYSQL_PORT=3306
      - MYSQL_IP=bccdb
    container_name: "policy_gateway"

  policy_token_gateway:
    image: "capstonegroup30/policy_token_gateway:latest"
    ports:
      - "5010:8080"
    depends_on:
      - "multichain"
    environment:
      - DEBUG=1
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_DATABASE=main
      - MYSQL_HOST=bccdb
      - PORT=8080

  fetcher:
    image: "capstonegroup30/fetcher:latest"
    ports:
      - "5080:80"
      - "5443:443"
    environment:
      - GOOGLE_API_CLIENT_ID=${GOOGLE_API_CLIENT_ID}
      - GOOGLE_API_CLIENT_SECRET=${GOOGLE_API_CLIENT_SECRET}
      - FITBIT_API_CLIENT_ID=${FITBIT_API_CLIENT_ID}
      - FITBIT_API_CLIENT_SECRET=${FITBIT_API_CLIENT_SECRET}
      
  bccdb:
    image: "capstonegroup30/bccdb:latest"
    ports:
      - "32233:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_DATABASE=main
      - PUID=1000
      - PGID=1000
      - BROKER_0=mock,mock_policy_drop_off:5000,minecraftisgood

  deployer:
    image: "capstonegroup30/policy_deployer:latest"
    ports:
      - "6080:80"
    environment:
      - VALIDATOR_IP=policy-validator
      - VALIDATOR_PORT=80
      - CHAIN_NAME=chain1
      - RPC_IP=multichain
      - RPC_PORT=25565
      - RPC_USERNAME=multichainrpc
      - RPC_PASSWORD=mypass

  multichain:
    image: "capstonegroup30/multichain-con:latest"
    ports:
      - "7090:25565"

  policy-validator:
    image: "capstonegroup30/policy-validator:latest"
    ports:
      - "7080:80"

  mock_policy_drop_off:
    image: "capstonegroup30/mock-policy-drop-off:dev"
    ports:
      - "7091:5000"
