version: '3'
services:
  policy_gateway:
    build: .
    ports:
      - "6010:5000"
    environment:
      - DEPLOYER_IP=${DOCKER_HOST_IP}:6080
      - FETCHER_IP=${DOCKER_HOST_IP}:5080
      - POLICY_TOKEN_IP=${DOCKER_HOST_IP}:5010
      - MYSQL_USERNAME=user
      - MYSQL_USER_PASSWORD=mypass
      - MYSQL_PORT=32233
      - MYSQL_IP=${DOCKER_HOST_IP}
    container_name: "policy_gateway"
  policy_token_gateway:
    image: "capstonegroup30/policy_token_gateway:latest"
    ports:
      - "5010:8080"
    container_name: "policy_token_gateway"
  fetcher:
    image: "capstonegroup30/fetcher:latest"
    ports:
      - "5080:80"
      - "5443:443"
    environment:
      - GOOGLE_API_CLIENT_ID=${GOOGLE_API_CLIENT_ID}
      - GOOGLE_API_CLIENT_SECRET=${GOOGLE_API_CLIENT_SECRET}
      - FITBIT_API_CLIENT_ID=${FITBIT_API_CLIENT_ID}
      - FITBIT_API_CLIENT_SECRET=${FITBIT_API_CLIENT_SECRET}
    container_name: "fetcher"
  deployer:
    image: "capstonegroup30/policy_deployer:latest"
    ports:
      - "6080:80"
      - "6443:443"
    environment:
      - VALIDATOR_IP=${DOCKER_HOST_IP}
      - VALIDATOR_PORT=7080
      - CHAIN_NAME=chain1
      - STREAM_NAME=stream1
      - RPC_IP=${DOCKER_HOST_IP}
      - RPC_PORT=7090
      - RPC_USERNAME=multichainrpc
      - RPC_PASSWORD=mypass
    container_name: "deployer"
  policy-validator:
    image: "capstonegroup30/policy-validator:latest"
    ports:
      - "7080:80"
    container_name: "policy-validator"
  bccdb:
    image: "capstonegroup30/bccdb:latest"
    ports:
      - "32233:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_DATABASE=main
      - PUID=1000
      - PGID=1000
      - SET_DEFAULT_BROKER=true
    container_name: "com_bccdb"
  multichain:
    image: "capstonegroup30/multichain-con:dev"
    ports:
      - "7090:25565"
    container_name: "multichain"
