##The docker compose file is for setting up the components for testing purposes

version: "3.3"
#Services is the top level list of the services to be configured in the file
services:
  app-token:
    #Path to the dockerfile relative to the location of the docker-compose file
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_DATABASE=db
      - PORT=8080
      - HOST=db
    volumes:
      - ./storage:/usr/src/app/storage

#Database 
  db:
    image: "capstonegroup30/bccdb:dev"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_DATABASE=db
      - PUID=1000
      - PGID=1000
      - SET_DEFAULT_BROKER=true