version: '3'
services:
  deployer:
    build: .
    ports:
      - "6080:80"
      - "6443:443"
    environment:
      - VALIDATOR_IP=policy-validator
      - VALIDATOR_PORT=7080
      - CHAIN_NAME=chain1
      - RPC_IP=${DOCKER_HOST_IP}
      - RPC_PORT=7090
      - RPC_USERNAME=multichainrpc
      - RPC_PASSWORD=mypass
    container_name: "deployer"
  policy-validator:
    image: "capstonegroup30/policy-validator:latest"
    ports:
      - "7080:80"
    container_name: "policy-validator"
  multichain:
    image: "capstonegroup30/multichain-con:latest"
    ports:
      - "7090:25565"
